name: Dependabot Fully automatic release

on: pull_request

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' # 仅在 Dependabot 提交 PR 时运行
    steps:
      - name: Enable auto-merge for Dependabot PRs
        if: contains(steps.metadata.outputs.dependency-names, 'electron') #&& steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
