name: Build/release

on:
  push:
    branches: [master]
  #release:
  #  types: [created]

permissions:
  contents: write

jobs:
  VersionBumpANDGitTag:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new,大版本更新"
          major-wording: "MAJOR,cut-major,新功能"
          patch-wording:
            "patch,fixes" # Providing patch-wording will override commits
            # defaulting to a patch bump.
          #rc-wording: "RELEASE,alpha"
          check-last-commit-only: "true"
